### ISSUE TITLE
Issue with Get Sectors.

### ISSUE THREAD

**Issue by imemohit** [dirkolbrich/yahoo-finance-query#12] opened 2015-06-24 18:50 UTC
On http://code.dirkolbrich.de/YahooFinanceQuery/example.php

Clicking on get sectors, returns 
Fatal error: Call to a member function get() on a non-object in /is/htdocs/wp1151455_Z2YVKT0TI9/code/YahooFinanceQuery/example.php on line 269

**Comment by dirkolbrich** [comment] 2015-06-25 14:30
Confirmed. The problem ist based an the YQL query. The underlying YQL table is actually a screen scrapper, witch fetches from http://biz.yahoo.com/ic/ind_index.html. Yahoo changed their site, wich breaks the table. See Issue https://github.com/tpowers/yql-tables/issues/5. 
I actually should write my own screen scrapper...

**Comment by dirkolbrich** [comment] 2015-09-28 15:12
fixed with custom screen scrapper 
https://github.com/dirkolbrich/yahoo-finance-query/commit/a71bcc4f1739270ed81d835b61b939eab92223ca

**Closed by dirkolbrich** 2015-09-28 15:12 UTC
